<?php
declare(strict_types=1);

$configDir     = __DIR__ . '/../config';
$envPath       = $configDir . '/.env';
$configPhpPath = $configDir . '/config.php';
$schemaPath    = __DIR__ . '/../sql/schema.sql';

// If already configured, short-circuit unless forced.
if (file_exists($envPath) && empty($_GET['force'])) {
    http_response_code(200);
    ?>
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Already configured</title>
        <style>
            body { font-family: 'Segoe UI', Tahoma, sans-serif; background: #0b1224; color: #e9eef7; display:flex; align-items:center; justify-content:center; min-height:100vh; margin:0; }
            .card { background: rgba(22,32,55,0.9); border:1px solid rgba(255,255,255,0.08); border-radius:14px; padding:1.5rem; max-width:520px; width:100%; box-shadow:0 10px 35px rgba(0,0,0,0.35); }
            h1 { margin:0 0 0.35rem; }
            p { color:#a9b8d9; line-height:1.5; }
            a.btn { display:inline-block; margin-top:0.75rem; padding:0.65rem 1rem; background: linear-gradient(135deg,#2ea8ff,#0d7adf); color:#0b1324; text-decoration:none; border-radius:10px; font-weight:700; }
            a.btn.secondary { background: transparent; color:#e9eef7; border:1px solid rgba(255,255,255,0.18); }
        </style>
    </head>
    <body>
    <div class="card">
        <h1>Setup already completed</h1>
        <p>We found <code>config/.env</code>. If you need to change values, you can delete that file and return here, or edit it manually.</p>
        <a class="btn" href="index.php">Go to dashboard</a>
        <a class="btn secondary" href="setup.php?force=1">Re-run setup anyway</a>
    </div>
    </body>
    </html>
    <?php
    exit;
}

$defaults = [
    'DB_HOST'                      => 'localhost',
    'DB_NAME'                      => 'qbo_pco_sync',
    'DB_USER'                      => 'qbopcosync',
    'DB_PASS'                      => '',
    'DB_CHARSET'                   => 'utf8mb4',
    'QBO_CLIENT_ID'                => '',
    'QBO_CLIENT_SECRET'            => '',
    'QBO_REDIRECT_URI'             => 'https://your-host/qbo-pco-sync/public/oauth-callback.php',
    'QBO_BASE_URL'                 => 'https://quickbooks.api.intuit.com',
    'QBO_ENVIRONMENT'              => 'production',
    'PCO_APP_ID'                   => '',
    'PCO_SECRET'                   => '',
    'PCO_BASE_URL'                 => 'https://api.planningcenteronline.com',
    'PCO_WEBHOOK_BATCH_CREATED'    => '',
    'PCO_WEBHOOK_BATCH_UPDATED'    => '',
    'PCO_WEBHOOK_DONATION_CREATED' => '',
    'PCO_WEBHOOK_DONATION_UPDATED' => '',
    'APP_BASE_URL'                 => 'https://your-host/qbo-pco-sync/public',
    'APP_NOTIFICATION_EMAIL'       => '',
    'MAIL_FROM'                    => '',
    'MAIL_SMTP_HOST'               => 'smtp.dreamhost.com',
    'MAIL_SMTP_PORT'               => '587',
    'MAIL_SMTP_USER'               => '',
    'MAIL_SMTP_PASS'               => '',
    'MAIL_SMTP_ENCRYPTION'         => 'tls',
];

$values = $defaults;
$errors = [];
$setupComplete = false;
$composerMissing = !file_exists(__DIR__ . '/../vendor/autoload.php');

function posted_value(string $key, array $defaults): string
{
    if (!isset($_POST[$key])) {
        return $defaults[$key] ?? '';
    }
    return trim((string)$_POST[$key]);
}

function quoted_value(string $value): string
{
    $safe = str_replace(["\r", "\n"], '', $value);
    $escaped = addcslashes($safe, "\\\"");
    return '"' . $escaped . '"';
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    foreach (array_keys($defaults) as $key) {
        $values[$key] = posted_value($key, $defaults);
    }

    // Basic validation
    $requiredKeys = [
        'DB_HOST', 'DB_NAME', 'DB_USER', 'DB_PASS',
        'QBO_CLIENT_ID', 'QBO_CLIENT_SECRET', 'QBO_REDIRECT_URI',
        'PCO_APP_ID', 'PCO_SECRET',
        'APP_BASE_URL', 'APP_NOTIFICATION_EMAIL', 'MAIL_FROM',
    ];
    foreach ($requiredKeys as $key) {
        if ($values[$key] === '') {
            $errors[] = $key . ' is required.';
        }
    }

    if (!preg_match('/^[A-Za-z0-9_]+$/', $values['DB_NAME'])) {
        $errors[] = 'DB_NAME may only contain letters, numbers, and underscores.';
    }
    if ($values['DB_CHARSET'] === '') {
        $errors[] = 'DB_CHARSET is required.';
    } elseif (!preg_match('/^[A-Za-z0-9_]+$/', $values['DB_CHARSET'])) {
        $errors[] = 'DB_CHARSET may only contain letters, numbers, and underscores.';
    }

    if (empty($errors)) {
        try {
            if (!is_dir($configDir) && !mkdir($configDir, 0775, true) && !is_dir($configDir)) {
                throw new RuntimeException('Unable to create config directory at ' . $configDir);
            }

            $envLines = ["# Generated by setup on " . date('c')];
            foreach ($values as $k => $v) {
                $envLines[] = $k . '=' . quoted_value($v);
            }
            $envContent = implode(PHP_EOL, $envLines) . PHP_EOL;
            if (file_put_contents($envPath, $envContent, LOCK_EX) === false) {
                throw new RuntimeException('Failed to write .env file.');
            }

            // Create config.php if missing (keeps repo version otherwise)
            if (!file_exists($configPhpPath)) {
                $template = <<<'PHP'
<?php
// Generated by setup.php

$envPath = __DIR__ . '/.env';
if (file_exists($envPath)) {
    $envLines = @file($envPath, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) ?: [];
    foreach ($envLines as $line) {
        $line = trim($line);
        if ($line === '' || str_starts_with($line, '#')) {
            continue;
        }
        [$k, $v] = array_pad(explode('=', $line, 2), 2, '');
        $k = trim($k);
        $v = trim($v, " \t\n\r\0\x0B\"'");
        if ($k !== '') {
            putenv($k . '=' . $v);
            $_ENV[$k] = $v;
        }
    }
}

function env_or_default(string $key, $default = null)
{
    $val = getenv($key);
    if ($val === false) {
        return $default;
    }
    return $val;
}

return [
    'db' => [
        'host'    => env_or_default('DB_HOST', ''),
        'name'    => env_or_default('DB_NAME', ''),
        'user'    => env_or_default('DB_USER', ''),
        'pass'    => env_or_default('DB_PASS', ''),
        'charset' => env_or_default('DB_CHARSET', 'utf8mb4'),
    ],
    'qbo' => [
        'client_id'     => env_or_default('QBO_CLIENT_ID', ''),
        'client_secret' => env_or_default('QBO_CLIENT_SECRET', ''),
        'redirect_uri'  => env_or_default('QBO_REDIRECT_URI', ''),
        'base_url'      => env_or_default('QBO_BASE_URL', 'https://quickbooks.api.intuit.com'),
        'environment'   => env_or_default('QBO_ENVIRONMENT', 'production'),
    ],
    'pco' => [
        'app_id'   => env_or_default('PCO_APP_ID', ''),
        'secret'   => env_or_default('PCO_SECRET', ''),
        'base_url' => env_or_default('PCO_BASE_URL', 'https://api.planningcenteronline.com'),
    ],
    'webhook_secrets' => [
        'giving.v2.events.batch.created'    => env_or_default('PCO_WEBHOOK_BATCH_CREATED', ''),
        'giving.v2.events.batch.updated'    => env_or_default('PCO_WEBHOOK_BATCH_UPDATED', ''),
        'giving.v2.events.donation.created' => env_or_default('PCO_WEBHOOK_DONATION_CREATED', ''),
        'giving.v2.events.donation.updated' => env_or_default('PCO_WEBHOOK_DONATION_UPDATED', ''),
    ],
    'app' => [
        'base_url'           => env_or_default('APP_BASE_URL', ''),
        'notification_email' => env_or_default('APP_NOTIFICATION_EMAIL', ''),
    ],
    'mail' => [
        'from'            => env_or_default('MAIL_FROM', ''),
        'smtp_host'       => env_or_default('MAIL_SMTP_HOST', ''),
        'smtp_port'       => (int)env_or_default('MAIL_SMTP_PORT', 587),
        'smtp_user'       => env_or_default('MAIL_SMTP_USER', ''),
        'smtp_pass'       => env_or_default('MAIL_SMTP_PASS', ''),
        'smtp_encryption' => env_or_default('MAIL_SMTP_ENCRYPTION', 'tls'),
    ],
];
PHP;
                if (file_put_contents($configPhpPath, $template, LOCK_EX) === false) {
                    throw new RuntimeException('Failed to write config.php file.');
                }
            }

            // Create DB and apply schema
            $dsn = 'mysql:host=' . $values['DB_HOST'] . ';charset=' . $values['DB_CHARSET'];
            $pdo = new PDO($dsn, $values['DB_USER'], $values['DB_PASS'], [
                PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            ]);

            $dbName = $values['DB_NAME'];
            $charset = $values['DB_CHARSET'];
            $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$dbName}` CHARACTER SET {$charset} COLLATE {$charset}_general_ci");
            $pdo->exec("USE `{$dbName}`");

            if (file_exists($schemaPath)) {
                $sql = file_get_contents($schemaPath);
                $sql = str_replace('qbo_pco_sync', $dbName, $sql);
                $statements = preg_split('/;\s*\n/', $sql);
                foreach ($statements as $stmt) {
                    $stmt = trim($stmt);
                    if ($stmt === '') {
                        continue;
                    }
                    $pdo->exec($stmt);
                }
            }

            $setupComplete = true;
        } catch (Throwable $e) {
            $errors[] = 'Setup failed: ' . $e->getMessage();
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>First-time setup</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Manrope:wght@500;700&display=swap');
        :root {
            --bg: #0b1224;
            --panel: rgba(15, 25, 46, 0.88);
            --border: rgba(255, 255, 255, 0.08);
            --text: #e9eef7;
            --muted: #9daccc;
            --accent: #2ea8ff;
            --accent-strong: #0d7adf;
            --error: #ff7a7a;
            --success: #39d98a;
        }
        * { box-sizing: border-box; }
        body {
            font-family: 'Manrope', 'Segoe UI', sans-serif;
            margin: 0;
            background: radial-gradient(circle at 18% 20%, rgba(46,168,255,0.14), transparent 32%),
                        radial-gradient(circle at 78% 10%, rgba(57,217,138,0.12), transparent 30%),
                        radial-gradient(circle at 65% 70%, rgba(242,201,76,0.08), transparent 35%),
                        var(--bg);
            color: var(--text);
            min-height: 100vh;
            padding: 1rem;
        }
        .layout { max-width: 980px; margin: 0 auto; }
        h1 { margin: 0 0 0.35rem; letter-spacing: -0.01em; }
        p.lede { margin: 0 0 1rem; color: var(--muted); }
        .panel {
            background: var(--panel);
            border: 1px solid var(--border);
            border-radius: 18px;
            padding: 1.25rem 1.5rem;
            box-shadow: 0 12px 40px rgba(0,0,0,0.28);
        }
        .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: 1rem; }
        label { font-weight: 700; display:block; margin-bottom: 0.35rem; }
        input[type="text"], input[type="password"], input[type="email"], input[type="url"] {
            width: 100%; padding: 0.65rem 0.75rem;
            border-radius: 10px; border: 1px solid rgba(255,255,255,0.14);
            background: rgba(255,255,255,0.05); color: var(--text); font-size: 0.95rem;
        }
        input:focus { outline: 2px solid rgba(46,168,255,0.4); border-color: rgba(46,168,255,0.45); }
        .section-title { margin-top:1rem; font-size: 1rem; color: #dfe8ff; }
        .error-box, .success-box {
            border-radius: 12px; padding: 0.9rem 1rem; margin-bottom: 1rem;
        }
        .error-box { background: rgba(255,122,122,0.12); border:1px solid rgba(255,122,122,0.35); color: #ffe0e0; }
        .success-box { background: rgba(57,217,138,0.12); border:1px solid rgba(57,217,138,0.35); color: #d1ffe7; }
        button {
            margin-top:1rem; padding:0.75rem 1.25rem;
            border:none; border-radius:12px;
            background: linear-gradient(135deg, var(--accent), var(--accent-strong));
            color:#0b1324; font-weight:700; cursor:pointer;
            box-shadow: 0 10px 25px rgba(13,122,223,0.32);
        }
        .footer { margin-top:1rem; color: var(--muted); font-size: 0.9rem; }
        .group { border:1px solid var(--border); border-radius:12px; padding:0.75rem 0.9rem; }
    </style>
</head>
<body>
<div class="layout">
    <h1>First-time setup</h1>
    <p class="lede">Provide your database, QuickBooks, and PCO credentials. We'll generate <code>config/.env</code>, create the database (and tables), and let you create the first admin user.</p>

<?php if (!empty($errors)): ?>
    <div class="error-box">
        <?php foreach ($errors as $err): ?>
            <div><?= htmlspecialchars($err, ENT_QUOTES, 'UTF-8') ?></div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>

<?php if ($composerMissing): ?>
    <div class="error-box">
        <div><strong>PHPMailer not installed.</strong></div>
        <div>Run <code>composer install</code> in the project root to download dependencies (needed for SMTP email).</div>
    </div>
<?php endif; ?>

<?php if ($setupComplete): ?>
    <div class="success-box">
        Setup complete. <strong>config/.env</strong> was written and the database was initialized.
        You can now <a href="login.php">log in</a> and create the first admin user.
    </div>
    <?php endif; ?>

    <?php if (!$setupComplete): ?>
    <form method="post" action="setup.php">
        <div class="panel">
            <div class="group">
                <div class="section-title">Database</div>
                <div class="grid">
                    <div>
                        <label for="DB_HOST">DB host</label>
                        <input id="DB_HOST" name="DB_HOST" type="text" value="<?= htmlspecialchars($values['DB_HOST'], ENT_QUOTES, 'UTF-8') ?>" required>
                    </div>
                    <div>
                        <label for="DB_NAME">DB name</label>
                        <input id="DB_NAME" name="DB_NAME" type="text" value="<?= htmlspecialchars($values['DB_NAME'], ENT_QUOTES, 'UTF-8') ?>" required>
                    </div>
                    <div>
                        <label for="DB_USER">DB user</label>
                        <input id="DB_USER" name="DB_USER" type="text" value="<?= htmlspecialchars($values['DB_USER'], ENT_QUOTES, 'UTF-8') ?>" required>
                    </div>
                    <div>
                        <label for="DB_PASS">DB password</label>
                        <input id="DB_PASS" name="DB_PASS" type="password" value="<?= htmlspecialchars($values['DB_PASS'], ENT_QUOTES, 'UTF-8') ?>" required>
                    </div>
                    <div>
                        <label for="DB_CHARSET">DB charset</label>
                        <input id="DB_CHARSET" name="DB_CHARSET" type="text" value="<?= htmlspecialchars($values['DB_CHARSET'], ENT_QUOTES, 'UTF-8') ?>" required>
                    </div>
                </div>
            </div>

            <div class="group">
                <div class="section-title">QuickBooks Online</div>
                <div class="grid">
                    <div>
                        <label for="QBO_CLIENT_ID">Client ID</label>
                        <input id="QBO_CLIENT_ID" name="QBO_CLIENT_ID" type="text" value="<?= htmlspecialchars($values['QBO_CLIENT_ID'], ENT_QUOTES, 'UTF-8') ?>" required>
                    </div>
                    <div>
                        <label for="QBO_CLIENT_SECRET">Client secret</label>
                        <input id="QBO_CLIENT_SECRET" name="QBO_CLIENT_SECRET" type="password" value="<?= htmlspecialchars($values['QBO_CLIENT_SECRET'], ENT_QUOTES, 'UTF-8') ?>" required>
                    </div>
                    <div>
                        <label for="QBO_REDIRECT_URI">Redirect URI</label>
                        <input id="QBO_REDIRECT_URI" name="QBO_REDIRECT_URI" type="url" value="<?= htmlspecialchars($values['QBO_REDIRECT_URI'], ENT_QUOTES, 'UTF-8') ?>" required>
                    </div>
                    <div>
                        <label for="QBO_BASE_URL">Base URL</label>
                        <input id="QBO_BASE_URL" name="QBO_BASE_URL" type="url" value="<?= htmlspecialchars($values['QBO_BASE_URL'], ENT_QUOTES, 'UTF-8') ?>">
                    </div>
                    <div>
                        <label for="QBO_ENVIRONMENT">Environment</label>
                        <input id="QBO_ENVIRONMENT" name="QBO_ENVIRONMENT" type="text" value="<?= htmlspecialchars($values['QBO_ENVIRONMENT'], ENT_QUOTES, 'UTF-8') ?>">
                    </div>
                </div>
            </div>

            <div class="group">
                <div class="section-title">Planning Center</div>
                <div class="grid">
                    <div>
                        <label for="PCO_APP_ID">App ID</label>
                        <input id="PCO_APP_ID" name="PCO_APP_ID" type="text" value="<?= htmlspecialchars($values['PCO_APP_ID'], ENT_QUOTES, 'UTF-8') ?>" required>
                    </div>
                    <div>
                        <label for="PCO_SECRET">Secret</label>
                        <input id="PCO_SECRET" name="PCO_SECRET" type="password" value="<?= htmlspecialchars($values['PCO_SECRET'], ENT_QUOTES, 'UTF-8') ?>" required>
                    </div>
                    <div>
                        <label for="PCO_BASE_URL">Base URL</label>
                        <input id="PCO_BASE_URL" name="PCO_BASE_URL" type="url" value="<?= htmlspecialchars($values['PCO_BASE_URL'], ENT_QUOTES, 'UTF-8') ?>">
                    </div>
                </div>
                <div class="section-title">Webhook secrets</div>
                <div class="grid">
                    <div>
                        <label for="PCO_WEBHOOK_BATCH_CREATED">giving.v2.events.batch.created</label>
                        <input id="PCO_WEBHOOK_BATCH_CREATED" name="PCO_WEBHOOK_BATCH_CREATED" type="text" value="<?= htmlspecialchars($values['PCO_WEBHOOK_BATCH_CREATED'], ENT_QUOTES, 'UTF-8') ?>">
                    </div>
                    <div>
                        <label for="PCO_WEBHOOK_BATCH_UPDATED">giving.v2.events.batch.updated</label>
                        <input id="PCO_WEBHOOK_BATCH_UPDATED" name="PCO_WEBHOOK_BATCH_UPDATED" type="text" value="<?= htmlspecialchars($values['PCO_WEBHOOK_BATCH_UPDATED'], ENT_QUOTES, 'UTF-8') ?>">
                    </div>
                    <div>
                        <label for="PCO_WEBHOOK_DONATION_CREATED">giving.v2.events.donation.created</label>
                        <input id="PCO_WEBHOOK_DONATION_CREATED" name="PCO_WEBHOOK_DONATION_CREATED" type="text" value="<?= htmlspecialchars($values['PCO_WEBHOOK_DONATION_CREATED'], ENT_QUOTES, 'UTF-8') ?>">
                    </div>
                    <div>
                        <label for="PCO_WEBHOOK_DONATION_UPDATED">giving.v2.events.donation.updated</label>
                        <input id="PCO_WEBHOOK_DONATION_UPDATED" name="PCO_WEBHOOK_DONATION_UPDATED" type="text" value="<?= htmlspecialchars($values['PCO_WEBHOOK_DONATION_UPDATED'], ENT_QUOTES, 'UTF-8') ?>">
                    </div>
                </div>
            </div>

            <div class="group">
                <div class="section-title">App</div>
                <div class="grid">
                    <div>
                        <label for="APP_BASE_URL">App base URL</label>
                        <input id="APP_BASE_URL" name="APP_BASE_URL" type="url" value="<?= htmlspecialchars($values['APP_BASE_URL'], ENT_QUOTES, 'UTF-8') ?>" required>
                    </div>
                    <div>
                        <label for="APP_NOTIFICATION_EMAIL">Notification email</label>
                        <input id="APP_NOTIFICATION_EMAIL" name="APP_NOTIFICATION_EMAIL" type="email" value="<?= htmlspecialchars($values['APP_NOTIFICATION_EMAIL'], ENT_QUOTES, 'UTF-8') ?>" required>
                    </div>
                    <div>
                        <label for="MAIL_FROM">Mail from</label>
                        <input id="MAIL_FROM" name="MAIL_FROM" type="email" value="<?= htmlspecialchars($values['MAIL_FROM'], ENT_QUOTES, 'UTF-8') ?>" required>
                    </div>
                </div>
                <div class="section-title">SMTP (recommended)</div>
                <p class="muted">Use your DreamHost mailbox for reliable delivery. Leave blank to fall back to PHP <code>mail()</code> (not recommended).</p>
                <div class="grid">
                    <div>
                        <label for="MAIL_SMTP_HOST">SMTP host</label>
                        <input id="MAIL_SMTP_HOST" name="MAIL_SMTP_HOST" type="text" value="<?= htmlspecialchars($values['MAIL_SMTP_HOST'], ENT_QUOTES, 'UTF-8') ?>" placeholder="smtp.dreamhost.com">
                    </div>
                    <div>
                        <label for="MAIL_SMTP_PORT">SMTP port</label>
                        <input id="MAIL_SMTP_PORT" name="MAIL_SMTP_PORT" type="number" value="<?= htmlspecialchars($values['MAIL_SMTP_PORT'], ENT_QUOTES, 'UTF-8') ?>" placeholder="587">
                    </div>
                    <div>
                        <label for="MAIL_SMTP_ENCRYPTION">Encryption (tls/ssl)</label>
                        <input id="MAIL_SMTP_ENCRYPTION" name="MAIL_SMTP_ENCRYPTION" type="text" value="<?= htmlspecialchars($values['MAIL_SMTP_ENCRYPTION'], ENT_QUOTES, 'UTF-8') ?>" placeholder="tls">
                    </div>
                    <div>
                        <label for="MAIL_SMTP_USER">SMTP username</label>
                        <input id="MAIL_SMTP_USER" name="MAIL_SMTP_USER" type="text" value="<?= htmlspecialchars($values['MAIL_SMTP_USER'], ENT_QUOTES, 'UTF-8') ?>" placeholder="you@your-domain.com">
                    </div>
                    <div>
                        <label for="MAIL_SMTP_PASS">SMTP password</label>
                        <input id="MAIL_SMTP_PASS" name="MAIL_SMTP_PASS" type="password" value="<?= htmlspecialchars($values['MAIL_SMTP_PASS'], ENT_QUOTES, 'UTF-8') ?>">
                    </div>
                </div>
            </div>

            <button type="submit">Save and initialize</button>
            <div class="footer">After saving, you'll be redirected to log in and can create the first admin user.</div>
        </div>
    </form>
    <?php endif; ?>
</div>
</body>
</html>
